project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - about.qmd
    - events.qmd
    - events/ystad2025/intro.qmd
    - events/ystad2025/menti.qmd

website:
  title: "Systems thinking"
  navbar:
    logo: assets/logos/nbislogo-green.svg
    favicon: assets/logos/nbislogo-green.svg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Events
        href: events.qmd
  page-footer:
    border: false
    left: "2025 [NBIS](https://nbis.se) | [GPL-3 License](https://choosealicense.com/licenses/gpl-3.0/)"
    right: "Published with [Quarto](https://quarto.org/) v<?quarto.version?>"


institute: NBIS
bibliography: assets/bibliography.bib
csl: assets/presentation.csl
from: markdown+emoji

format:
  nbis-course-html:
    toc: true
    embed-resources: false
    date: last-modified
    date-format: "DD-MMM-YYYY"
    code-link: true
    code-block-border-left: "#a7c947"
    lightbox:
      match: auto
  nbis-course-revealjs:
    theme: [default, assets/css/custom.scss]
    toc: false
    toc-depth: 2
    slide-level: 2
    slide-number: true
    preview-links: true
    chalkboard: false
    footer: Systems thinking
    smaller: true
    highlight-style: gruvbox
    fig-height: 3
    fig-width: 3
    fig-align: center
    text-align: center
    width: 1050
    height: 700
    margin: 0.05
    navigation-mode: vertical
    ultitle: true
    nbistitlelogo: false
    embed-resources: false


knitr:
  opts_chunk:
    code-fold: false
    tidy: true
    comment-char: "#>"
    fig-format: svg
    engine.opts:
      dvisvgm.opts: --font-format=woff
      template: tikzfig.tex

filters:
  - nbis-course

extensions:
  - nbis-course
  - fontawesome
