[project]
authors = ["Per Unneberg <per.unneberg@scilifelab.se>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "SystemsThinking"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
"r-data.table" = ">=1.17.0,<2"
r = ">=4.4,<4.5"
r-base = ">=4.4.3,<4.5"
r-devtools = ">=2.4.5,<3"
r-ggplot2 = ">=3.5.2,<4"
r-viridis = ">=0.6.5,<0.7"
r-latex2exp = ">=0.9.6,<0.10"
r-kableextra = ">=1.4.0,<2"
r-tidyverse = ">=2.0.0,<3"
r-ggtext = ">=0.1.2,<0.2"
r-plotly = ">=4.10.4,<5"
xlrd = ">=2.0.1,<3"
r-formatr = ">=1.14,<2"
r-reticulate = ">=1.40.0,<2"
r-rmarkdown = ">=2.29,<3"
